version: "3.9"

services:
  nats: 
    image: nats
    ports:
      - 8222:8222
      - 4222:4222
      - 6222:6222
    command: [ "-js" ]
  rates:
    build:
      context: rates
    depends_on: 
      - nats
    environment:
      - NATS_HOST=nats